language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "10.16"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$access_key_id"
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1b"
  app: "mychess"
  env: "Mychess-env"
  bucket_name: "lv428chess"
